02_03-asp-net-core-entity-framework/entity/Models/Categoria.cs
namespace entity.Models
{
    public class Categoria
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public override string ToString()
        {
            return $"Id: {this.Id}, Categoria: {this.Nome}";
        }
    }
}

02_03-asp-net-core-entity-framework/entity/Models/ErrorViewModel.cs
using System;

namespace entity.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

02_03-asp-net-core-entity-framework/entity/Models/Funcionario.cs
using System;


namespace entity.Models
{
    public class Funcionario
    {
      public int Id { get; set; }
      public string Nome { get; set; }
      public float Salario { get; set; }
      public string Cpf { get; set; }
    }
}

02_03-asp-net-core-entity-framework/entity/Models/Produto.cs
namespace entity.Models
{
    public class Produto
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public virtual Categoria Categoria { get; set; }

        public override string ToString()
        {
            return $"Id: {this.Id}, Nome: {this.Nome}, Categoria[{this.Categoria.ToString()}]";
        }
    }
}

02_03-asp-net-core-entity-framework/entity/Controllers/EmployeeController.cs
using System;
using System.Globalization;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using entity.Models;
using entity.Database;

namespace entity.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly ApplicationDBContext Database; //readonly significa que só pode ser alterado aqui e no construtor
        public FuncionariosController(ApplicationDBContext database) {
        //Injeção de dependencia do objeto ApplicationDBContext na Controller
            this.Database = database;
        }

        public IActionResult Index(){
            var funcionarios = Database.Funcionarios.ToList();
            return View(funcionarios);
        }

        public IActionResult Cadastrar(){
            return View();
        }

        //o parametro int id já é padrão e opcional nas rotas asp.net, por isso não tem necessidade de passar argumentos via HttpGet("url") 
        public IActionResult Editar(int id){
            Funcionario funcionario = Database.Funcionarios.First(func => func.Id == id); //busca uma query no banco de dados a partir do id
            return View("Cadastrar", funcionario);
        }
        public IActionResult Excluir(int id){
            Funcionario funcionario = Database.Funcionarios.First(func => func.Id == id); //busca uma query no banco de dados a partir do id
            Database.Funcionarios.Remove(funcionario);
            Database.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Salvar(Funcionario funcionario){
            if(funcionario.Id == 0){
                //adicionar novo funcionario
                Database.Funcionarios.Add(funcionario);
            }else{
                //atualizar cadastro do funcionario
                Funcionario funcionarioDB = Database.Funcionarios.First(func => func.Id == funcionario.Id);
                //modificacoes diretas na variavel funcionarioDB vem do banco de dados e suas alterações são aplicadas no banco de dados 
                funcionarioDB.Nome = funcionario.Nome;
                funcionarioDB.Salario = funcionario.Salario;
                funcionarioDB.Cpf = funcionario.Cpf;
            }
            Database.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

02_03-asp-net-core-entity-framework/entity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using entity.Models;
using entity.Database;
using Microsoft.EntityFrameworkCore;

namespace entity.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDBContext Database; //readonly significa que só pode ser alterado aqui e no construtor
        public HomeController(ApplicationDBContext database) {
        //Injeção de dependencia do objeto ApplicationDBContext na Controller
            this.Database = database;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Teste()
        {
            // Categoria c1 = new Categoria();
            // Categoria c2 = new Categoria();
            // Categoria c3 = new Categoria();
            // Categoria c4 = new Categoria();
            // Categoria c5 = new Categoria();
            // c1.Nome = "Administrador";
            // c2.Nome = "Gerente";
            // c3.Nome = "Funcionario";
            // c4.Nome = "Guest";
            // c5.Nome = "Guest";
            // List<Categoria> listaCat = new List<Categoria>();
            // listaCat.Add(c1);
            // listaCat.Add(c2);
            // listaCat.Add(c3);
            // listaCat.Add(c4);
            // listaCat.Add(c5);
            // Database.AddRange(listaCat);
            // Database.SaveChanges();

            var listaDeCategorias = Database.Categorias.Where(c => c.Nome.Equals("Guest") || c.Id % 2 == 0).ToList();
            string itens = "";
            foreach (var item in listaDeCategorias) {
                System.Console.WriteLine(item);
                itens += item + "\n";
            }
            return Content(itens);
        }

        public IActionResult Relacionamento()
        {
            // Produto p1 = new Produto();
            // p1.Nome = "Doritos";
            // p1.Categoria = Database.Categorias.First(c => c.Id == 1);
            // Produto p2 = new Produto();
            // p2.Nome = "Fandangos";
            // p2.Categoria = Database.Categorias.First(c => c.Id == 2);
            // Produto p3 = new Produto();
            // p3.Nome = "Cheetos";
            // p3.Categoria = Database.Categorias.First(c => c.Id == 2);
            // Database.Add(p1);
            // Database.Add(p2);
            // Database.Add(p3);
            // Database.SaveChanges();


             //O entiy framework não inclui automaticamente instancia de outras classes, então é preciso usar o include dessa classe
            /*var listaProdutos = Database.Produtos.Include(p => p.Categoria).ToList();

            string itens = "";
            listaProdutos.ForEach(produto =>{
                Console.WriteLine(produto);
                itens += produto + "\n";
            });*/

            //consultando vários elementos com base em um atributo, usando LazyLoading, mas evite usá-lo
            var produtosEspecificos = Database.Produtos./*Include(p => p.Categoria).*/Where(p => p.Categoria.Id == 2).ToList();
            string itens = "";
            produtosEspecificos.ForEach(p =>{
                System.Console.WriteLine(p);
                itens += p + "\n";
            });



            return Content(itens);
        }

    }
}

02_03-asp-net-core-entity-framework/entity/Views/Funcionarios/Cadastrar.cshtml
@model entity.Models.Funcionario;

<div>
    <h2>Cadastro de Funcionários</h2>
    <a href="/Funcionarios/Index" class="btn btn-primary">Voltar</a>
    <form class="form-horizontal" asp-controller="Funcionarios" asp-action="Salvar" method="post">
        <input type="hidden"asp-for="Id">

        Nome: <input type="text" class="form-control" asp-for="Nome" placeholder="Nome">
        Salario: R$<input type="number" class="form-control" asp-for="Salario" placeholder="Salario">
        CPF: <input type="text" class="form-control" asp-for="Cpf" placeholder="CPF">
        
        <button class="btn-success">Cadastrar</button>
    </form>
</div>

02_03-asp-net-core-entity-framework/entity/Views/Funcionarios/Index.cshtml
@model IEnumerable<entity.Models.Funcionario>

<div class="content" style="text-align: center;">
    <h2>Funcionários</h2>
    <a href="/Funcionarios/Cadastrar" class="btn btn-success">Cadastrar Novo Funcionário</a>
        @foreach (var funcionario in Model){
            <p>CPF: @funcionario.Cpf, Nome: @funcionario.Nome, Salario: R$@funcionario.Salario
                <div>
                    <a href="/Funcionarios/Editar/@funcionario.Id" class="btn btn-warning">Editar</a>
                    <a href="/Funcionarios/Excluir/@funcionario.Id" class="btn btn-danger">Excluir</a>
                </div>
            </p>
            <hr>
        }
</div>

02_03-asp-net-core-entity-framework/entity/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a href="Funcionarios/Index" class="btn btn-success">Ver Funcionários</a>
</div>

02_03-asp-net-core-entity-framework/entity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - entity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">entity</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - entity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>