09-projeto-aspnet-mercado/PortellaMarket/Controllers/GestaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PortellaMarket.Data;
using PortellaMarket.DTO;
using PortellaMarket.Models;

namespace PortellaMarket.Controllers
{
    [Authorize]
    public class GestaoController : Controller
    {
        private readonly ApplicationDbContext Database;

        public GestaoController(ApplicationDbContext database){
            Database = database;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Categorias()
        {
            var categorias = Database.Categorias.Where(c => c.Status == true).ToList();
            return View(categorias);
        }
        
        public IActionResult NovaCategoria()
        {
            return View();
        }

        public IActionResult EditarCategoria(int id)
        {
            var categoria = Database.Categorias.First(c => c.Id == id);

            //A view EditarCategoria só recebe dados do tipo CategoriaDTO, então é preciso criar uma CategoriaDTO para receber os dados
            CategoriaDTO categoriaView = new CategoriaDTO();
            categoriaView.Id = categoria.Id;
            categoriaView.Nome = categoria.Nome;

            return View(categoriaView);
        }

        public IActionResult Fornecedores()
        {
            var fornecedores = Database.Fornecedores.Where(f => f.Status == true).ToList();
            return View(fornecedores);
        }

        public IActionResult NovoFornecedor()
        {
            return View();
        }

        public IActionResult EditarFornecedor(int id)
        {
            var fornecedor = Database.Fornecedores.First(f => f.Id == id);

            FornecedorDTO fornecedorView = new FornecedorDTO();
            fornecedorView.Id = fornecedor.Id;
            fornecedorView.Nome = fornecedor.Nome;
            fornecedorView.Email = fornecedor.Email;
            fornecedorView.Telefone = fornecedor.Telefone;
            
            return View(fornecedorView);
        }

        public IActionResult Produtos()
        {
            var produtos = Database.Produtos.Include(p => p.Categoria).Include(p => p.Fornecedor).Where(p => p.Status == true).ToList();
            return View(produtos);
        }

        public IActionResult NovoProduto()
        {
            ViewBag.Categorias = Database.Categorias.ToList();
            ViewBag.Fornecedores = Database.Fornecedores.ToList();
            return View();
        }

        public IActionResult EditarProduto(int id)
        {
            var produto = Database.Produtos.Include(p => p.Categoria).Include(p => p.Fornecedor).First(p => p.Id == id);
            ProdutoDTO produtoView = new ProdutoDTO();
            produtoView.Id= produto.Id;
            produtoView.Nome = produto.Nome;
            produtoView.CategoriaId = produto.Categoria.Id;
            produtoView.FornecedorId = produto.Fornecedor.Id;
            produtoView.PrecoDeCusto = produto.PrecoDeCusto;
            produtoView.PrecoDeVenda = produto.PrecoDeVenda;
            produtoView.Medicao = produto.Medicao;

            ViewBag.Categorias = Database.Categorias.ToList();
            ViewBag.Fornecedores = Database.Fornecedores.ToList();
            
            return View(produtoView);
        }

        public IActionResult Promocoes()
        {
            var promocoes = Database.Promocoes.Include(p => p.Produto).Where(p => p.Status == true).ToList();
            return View(promocoes);
        }

        public IActionResult NovaPromocao()
        {
            ViewBag.Produtos = Database.Produtos.ToList();
            return View();
        }

        public IActionResult EditarPromocao(int id)
        {
            var promocao = Database.Promocoes.Include(p => p.Produto).First(p => p.Id == id);
            PromocaoDTO promocaoView = new PromocaoDTO();
            promocaoView.Id= promocao.Id;
            promocaoView.Nome = promocao.Nome;
            promocaoView.ProdutoId = promocao.Produto.Id;
            promocaoView.Porcentagem = promocao.Porcentagem;

            ViewBag.Produtos = Database.Produtos.ToList();
            
            return View(promocaoView);
        }

        public IActionResult Estoque()
        {
            var listaEstoques = Database.Estoques.Include(p => p.Produto).ToList();
            return View(listaEstoques);
        }

        public IActionResult NovoEstoque()
        {
            ViewBag.Produtos = Database.Produtos.ToList();
            return View();
        }
        public IActionResult EditarEstoque(int id)
        {
            var estoque = Database.Estoques.Include(e => e.Produto).First(p => p.Id == id);
            Estoque estoqueView = new Estoque();
            estoqueView.Id= estoque.Id;
            estoqueView.ProdutoId = estoque.Produto.Id;
            estoqueView.Quantidade = estoque.Quantidade;

            ViewBag.Produtos = Database.Produtos.ToList();
            
            return View(estoqueView);
        }

        public IActionResult Vendas()
        {
            var relatorioVendas = Database.Vendas.ToList();
            return View(relatorioVendas);
        }

        [HttpPost]
        public IActionResult RelatorioDeVendas()
        {
            return base.Ok(Database.Vendas.ToList());
        }
    }
}

09-projeto-aspnet-mercado/PortellaMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PortellaMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PortellaMarket</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PortellaMarket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

09-projeto-aspnet-mercado/PortellaMarket/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portella Market - Admin</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="~/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Datatables CSS
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
    -->

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin.css" rel="stylesheet">

    <!-- JQuery -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- DataTables -->
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

</head>


<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <a class="navbar-brand mr-1" asp-controller="Home" asp-action="Index">Portella Market</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Navbar Search -->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            @* <div class="input-group">
                <input type="text" class="form-control" placeholder="Pesquise alguma coisa..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div> *@
        </form>

        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
                </div>
            </li>
        </ul>

    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Gestao" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Gestao" asp-action="Categorias">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Categorias</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Gestao" asp-action="Fornecedores">
                    <i class="fas fa-fw fa-people-carry"></i>
                    <span>Fornecedores</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Gestao" asp-action="Produtos">
                    <i class="fas fa-fw fa-boxes"></i>
                    <span>Produtos</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Gestao" asp-action="Promocoes">
                    <i class="fas fa-fw fa-percent"></i>
                    <span>Promoções</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Gestao" asp-action="Estoque">
                    <i class="fas fa-fw fa-truck-loading"></i>
                    <span>Estoque</span>
                </a>
            </li>
            @*<li class="nav-item">
                <a class="nav-link" asp-controller="Gestao" asp-action="Unidades">
                    <i class="fas fa-fw fa-ruler"></i>
                    <span>Unidades</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Gestao" asp-action="Vendas">
                    <i class="fas fa-fw fa-cash-register"></i>
                    <span>Vendas</span>
                </a> *@
            </li>
        </ul>

        <div id="content-wrapper">

            <div class="container-fluid">

                <h2>@ViewData["Title"]</h2>

                <!-- Breadcrumbs-->
                @* <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Gestao" asp-action="index">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item active">Blank Page</li>
                </ol> *@

                <!-- Page Content -->
                @RenderBody()

            </div>
            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            @* <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © MarktSys @DateTime.Now.Year</span>
                    </div>
                </div>
            </footer> *@

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
</body>

</html>